### ISSUE TITLE
Can't save state

### ISSUE THREAD

**Issue by not-well** [flathub/com.fightcade.Fightcade#122]
When I try to save a state on FB Neo I've got a warning saying "Error creating state file". To reproduce the problem when the emulator start go to Game > Save states > Save state or use the shortcut Ctrl + F10.

I can't found any logs to put here, the only test that I made was put an old save file that I've had a on /var/lib/flatpak/app/com.fightcade.Fightcade/current/active/files/fightcade/Fightcade/emulator/fbneo/savestates and the file was loaded properly when I searched using Load state function or Ctrl + F9.

**Comment by Pobega** [comment]
This may be fixable but it's not something I've considered, is there a reason you need to use save states? I primarily focus on the supporting multiplayer and not using FBNeo as a single player emulator (considering [MAME](https://flathub.org/apps/details/org.mamedev.MAME) is available and runs natively (rather than through Wine like FBNeo))

**Comment by not-well** [comment]
I generally use it for NeoGeo games that has training mode and Lua scripts, so this way I can skip to a desired circumstance without having to switch every time on the dip switches to AES mode. But I understand that this should not be a priority, I just reported the problem.

**Comment by Pobega** [comment]
I see the issue. That directory is currently read-only and ships with all of the default save states (which I believe are loaded when you connect to another player to skip you to character select.)

Allowing write access to the directory isn't hard but I'm a bit concerned with the states being overwritten causing new bugs. Additionally because of the way I've implemented things any changes to files that already exist in that directory would be overwritten when you launch Fightcade.

Could you explain a bit more about the use case and if these limitations would be sufficient?

**Comment by Pobega** [comment]
Give this build a try and let me know how it works for you; https://github.com/flathub/com.fightcade.Fightcade/pull/124

**Comment by not-well** [comment]
The notebook that I was using while opened this issue is not working anymore. But the problem only occurs when I was trying to save a state, loading was ok, and if I get a save state from an external source and put it in the states folder I could load it normally.

**Comment by Pobega** [comment]
I'm not sure what you mean about the notebook, can you elaborate?

The development build I provided should have a r/w save state directory and allow you do save state using Ctrl+F10 in-emulator.

**Comment by not-well** [comment]
Sorry, I used an brazilian expression, notebook is what we call laptop.
The default save states should not be overriden, this is generally used when the emulator loads the game for netplay, usually is the save states with _fbneo at its name. But when you press Ctrl + F10 the emulator prompts to choose a name for the new save state, and generally suggests a different name from default save state.

**Comment by Pobega** [comment]
Should be resolved by #124
