### ISSUE TITLE
Outdated flatpak package

### ISSUE THREAD

**Issue by ceteco** [flathub/com.fightcade.Fightcade#24]
Can't run Fightcade, says it's outdated.
![image](https://user-images.githubusercontent.com/1707268/114174283-a5bd7b00-98f5-11eb-8502-c0c9145a02a0.png)
Help!

**Comment by Pobega** [comment]
Updates are handled automatically by the Flathub bot. It seems there was [an update this morning to 2.0.97](https://github.com/flathub/com.fightcade.Fightcade/pull/23) which got pulled back for some reason [a few hours later](https://github.com/flathub/com.fightcade.Fightcade/pull/25)

pof just announced 2.0.98 so that should be updated soon.

Keep in mind there's a lag between the code being updated and the package on Flathub being updated and there isn't much I can do about that. Just give it a few hours and be patient
